/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int DO = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FALSE = 14;
  int IF = 15;
  int IMPORT = 16;
  int INSTANCEOF = 17;
  int INT = 18;
  int NEW = 19;
  int NULL = 20;
  int PACKAGE = 21;
  int PRIVATE = 22;
  int PROTECTED = 23;
  int PUBLIC = 24;
  int RETURN = 25;
  int STATIC = 26;
  int SUPER = 27;
  int THIS = 28;
  int TRUE = 29;
  int VOID = 30;
  int WHILE = 31;
  int PLUS = 32;
  int ASSIGN = 33;
  int DEC = 34;
  int EQUAL = 35;
  int GT = 36;
  int INC = 37;
  int LAND = 38;
  int LE = 39;
  int LSHIFT = 40;
  int LNOT = 41;
  int MINUS = 42;
  int PLUS_ASSIGN = 43;
  int STAR = 44;
  int LPAREN = 45;
  int RPAREN = 46;
  int LCURLY = 47;
  int RCURLY = 48;
  int LBRACK = 49;
  int RBRACK = 50;
  int SEMI = 51;
  int COMMA = 52;
  int DOT = 53;
  int IDENTIFIER = 54;
  int LETTER = 55;
  int DIGIT = 56;
  int NON_ZERO_DIGIT = 57;
  int INT_LITERAL = 58;
  int BINT_LITERAL = 59;
  int BINT_TYPE = 60;
  int XINT_LITERAL = 61;
  int XINT_TYPE = 62;
  int CHAR_LITERAL = 63;
  int STRING_LITERAL = 64;
  int ESC = 65;
  int ERROR = 66;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"<<\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<BINT_LITERAL>",
    "<BINT_TYPE>",
    "<XINT_LITERAL>",
    "<XINT_TYPE>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
