/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int DO = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FALSE = 14;
  int FOR = 15;
  int IF = 16;
  int IMPORT = 17;
  int INSTANCEOF = 18;
  int INT = 19;
  int NEW = 20;
  int NULL = 21;
  int PACKAGE = 22;
  int PRIVATE = 23;
  int PROTECTED = 24;
  int PUBLIC = 25;
  int RETURN = 26;
  int STATIC = 27;
  int SUPER = 28;
  int THIS = 29;
  int TRUE = 30;
  int VOID = 31;
  int WHILE = 32;
  int PLUS = 33;
  int ASSIGN = 34;
  int DEC = 35;
  int EQUAL = 36;
  int GT = 37;
  int INC = 38;
  int LAND = 39;
  int LE = 40;
  int LSHIFT = 41;
  int LNOT = 42;
  int MINUS = 43;
  int PLUS_ASSIGN = 44;
  int STAR = 45;
  int LPAREN = 46;
  int RPAREN = 47;
  int LCURLY = 48;
  int RCURLY = 49;
  int LBRACK = 50;
  int RBRACK = 51;
  int SEMI = 52;
  int COMMA = 53;
  int DOT = 54;
  int IDENTIFIER = 55;
  int LETTER = 56;
  int DIGIT = 57;
  int NON_ZERO_DIGIT = 58;
  int INT_LITERAL = 59;
  int BINT_LITERAL = 60;
  int BINT_TYPE = 61;
  int XINT_LITERAL = 62;
  int XINT_TYPE = 63;
  int CHAR_LITERAL = 64;
  int STRING_LITERAL = 65;
  int ESC = 66;
  int ERROR = 67;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"for\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"<<\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<BINT_LITERAL>",
    "<BINT_TYPE>",
    "<XINT_LITERAL>",
    "<XINT_TYPE>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
